(function(){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=ms=>Math.floor(ms/60000)+':'+String(Math.floor(ms/1000)%60).padStart(2,'0');
  const parseTime=value=>{const s=String(value||'').trim();if(/^\d+(?::[0-5]?\d)?$/.test(s)){const p=s.split(':').map(Number);return p.length===2?(p[0]*60+p[1])*1000:p[0]*1000}return Math.max(0,Number(s)||0);};
  const uid=()=> 'q_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
  function create(cfg){
    let course={interactions:[]}, questions=[], attempts=new Map(), asked=[], active=null, tab='interact';
    let lastMs=0, previewed='', sessionReady=false, authorQuestions=[], completed=false;
    const panel=document.createElement('aside'); panel.className='ll-interactions collapsed'; panel.setAttribute('aria-label','互动与学习反馈');
    panel.innerHTML='<button class="ll-side-toggle" title="展开互动侧栏（可拖动）" aria-label="展开互动侧栏" aria-expanded="false"><span class="ll-toggle-mark">L</span></button><div class="ll-side-content"><div class="ll-side-head"><strong>互动学习</strong><div class="ll-tabs"><button data-tab="interact" class="on">互动</button><button data-tab="records">学习记录</button></div></div><div class="ll-side-body"></div><div class="ll-ask"><textarea maxlength="1000" placeholder="针对当前讲解提问…"></textarea><div class="ll-ask-row"><span>将附带当前时间和课程内容</span><button>提问</button></div></div></div>';
    (cfg.stage.querySelector('#workarea')||cfg.stage).appendChild(panel);
    const body=panel.querySelector('.ll-side-body'), toggle=panel.querySelector('.ll-side-toggle');
    const badge=document.createElement('span');badge.className='badge';badge.hidden=true;toggle.appendChild(badge);
    function setCollapsed(collapsed){panel.classList.toggle('collapsed',collapsed);panel.classList.add('show');toggle.setAttribute('aria-expanded',String(!collapsed));toggle.setAttribute('aria-label',collapsed?'展开互动侧栏':'收起互动侧栏');toggle.title=collapsed?'展开互动侧栏（可拖动）':'收起互动侧栏';}
    let drag=null,moved=false;
    try{const pos=JSON.parse(localStorage.getItem('llInteractionFloat')||'null');if(pos){panel.style.setProperty('--ll-float-x',pos.x+'px');panel.style.setProperty('--ll-float-y',pos.y+'px');panel.style.setProperty('--ll-float-right','auto');}}catch(e){}
    toggle.addEventListener('pointerdown',e=>{if(!panel.classList.contains('collapsed'))return;drag={x:e.clientX,y:e.clientY};moved=false;toggle.setPointerCapture(e.pointerId);});
    toggle.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;const host=panel.parentElement.getBoundingClientRect();const x=Math.max(8,Math.min(host.width-58,e.clientX-host.left-25));const y=Math.max(8,Math.min(host.height-58,e.clientY-host.top-25));panel.style.setProperty('--ll-float-x',x+'px');panel.style.setProperty('--ll-float-y',y+'px');panel.style.setProperty('--ll-float-right','auto');});
    toggle.addEventListener('pointerup',()=>{if(drag&&moved){const x=parseFloat(getComputedStyle(panel).getPropertyValue('--ll-float-x'))||0,y=parseFloat(getComputedStyle(panel).getPropertyValue('--ll-float-y'))||0;try{localStorage.setItem('llInteractionFloat',JSON.stringify({x,y}));}catch(e){}}drag=null;});
    toggle.onclick=()=>{if(moved){moved=false;return;}setCollapsed(!panel.classList.contains('collapsed'));render();};
    panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;panel.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x===b));render();});
    panel.querySelector('.ll-ask button').onclick=askQuestion;
    cfg.playButton?.addEventListener('click',()=>setTimeout(()=>saveEvent(cfg.isPlaying?.()?'play':'pause',cfg.getPlaybackMs?.()||0),0));

    const seek=cfg.seek;
    const wrap=document.createElement('span');wrap.className='ll-seek-wrap';seek.parentNode.insertBefore(wrap,seek);wrap.appendChild(seek);
    const markers=document.createElement('span');markers.className='ll-marker-layer';wrap.appendChild(markers);

    function access(){return cfg.getAccess?cfg.getAccess():{};}
    async function api(path,options={}){
      const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
      const data=await res.json().catch(()=>({})); if(!res.ok)throw new Error(data.error||('HTTP '+res.status)); return data;
    }
    async function ensureSession(){
      const rid=cfg.getRecordingId?.(); if(!rid||sessionReady)return;
      try{const d=await api('/api/learn/session',{method:'POST',body:JSON.stringify({recording_id:rid,...access()})});sessionReady=true;(d.attempts||[]).forEach(a=>attempts.set(a.interaction_id,a));asked=d.questions||[];render();renderMarkers();}catch(e){cfg.notify?.('学习档案暂时不可用：'+e.message,true);}
    }
    function normalize(list){return (Array.isArray(list)?list:[]).filter(q=>q&&q.id&&['single_choice','short_answer'].includes(q.type)&&Number.isFinite(Number(q.atMs))).map(q=>({...q,approved:q.approved!==false,revision:Math.max(1,Number(q.revision)||1),atMs:Math.max(0,Number(q.atMs)||0),previewMs:Math.max(0,Number(q.previewMs??30000)||0),options:Array.isArray(q.options)?q.options:[],correctOptionIds:Array.isArray(q.correctOptionIds)?q.correctOptionIds:[]})).sort((a,b)=>a.atMs-b.atMs);}
    function setCourse(json){course=json||{};questions=normalize(course.interactions);authorQuestions=questions.map(q=>structuredClone(q));attempts.clear();asked=[];active=null;lastMs=cfg.getPlaybackMs?.()||0;previewed='';completed=false;sessionReady=false;panel.classList.add('show');render();renderMarkers();void ensureSession();}
    function renderMarkers(){markers.replaceChildren();const dur=Math.max(1,(course.duration||0)*1000);for(const q of questions){const m=document.createElement('button');m.className='ll-marker '+(attempts.has(q.id)?'done':'pending');m.style.left=Math.min(100,q.atMs/dur*100)+'%';m.title=fmt(q.atMs)+' · '+q.prompt;m.onclick=()=>{cfg.seekTo?.(q.atMs);showQuestion(q,false);};markers.appendChild(m);}}
    function render(){
      badge.hidden=!(questions.some(q=>!attempts.has(q.id))||asked.some(q=>!q.author_reply));badge.textContent=String(questions.filter(q=>!attempts.has(q.id)).length+asked.filter(q=>!q.author_reply).length);
      if(tab==='records')return renderRecords();
      let h='';if(previewed){const q=questions.find(x=>x.id===previewed);if(q)h+='<div class="ll-upcoming">即将思考：'+esc(q.prompt)+'</div>';}
      if(active)h+=questionHtml(active);else h+='<div class="ll-empty">播放到问题点时会自动暂停。<br>你也可以随时在下方提问。</div>';
      body.innerHTML=h;bindQuestion();
    }
    function questionHtml(q){const old=attempts.get(q.id);let fields='';if(q.type==='single_choice')fields=q.options.map(o=>'<label class="ll-option"><input type="radio" name="ll-answer" value="'+esc(o.id)+'"> <span>'+esc(o.text)+'</span></label>').join('');else fields='<textarea class="ll-short" maxlength="2000" placeholder="用自己的话回答…"></textarea>';
      return '<div class="ll-q-card" data-q="'+esc(q.id)+'"><div class="ll-q-time">'+fmt(q.atMs)+' · '+(q.type==='single_choice'?'单选题':'简答题')+'</div><div class="ll-q-prompt">'+esc(q.prompt)+'</div>'+fields+'<div class="ll-actions"><button class="primary" data-act="submit">提交回答</button><button data-act="later">稍后回答</button></div>'+(old?feedbackHtml(old):'')+'</div>';}
    function feedbackHtml(a){const cls=a.result==='correct'||a.result==='理解正确'?'good':'warn';return '<div class="ll-feedback '+cls+'"><b>'+esc(a.result||'已保存')+'</b>\n'+esc(a.feedback||'')+(a.evidence?'\n依据本课：'+esc(a.evidence):'')+'</div>';}
    function bindQuestion(){const card=body.querySelector('[data-q]');if(!card)return;card.querySelector('[data-act="later"]').onclick=()=>{const q=active;active=null;saveEvent('skip',q?.atMs||0,q?.id);render();renderMarkers();resume();};card.querySelector('[data-act="submit"]').onclick=()=>submitAnswer(card);}
    function pause(){if(cfg.isPlaying?.())cfg.pause?.();}
    function resume(){cfg.resume?.();}
    function showQuestion(q,auto=true){active=q;previewed='';setCollapsed(false);tab='interact';panel.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab==='interact'));if(auto)pause();render();setTimeout(()=>body.querySelector('input,textarea')?.focus(),0);}
    async function submitAnswer(card){const q=active;if(!q)return;let answer;if(q.type==='single_choice')answer=card.querySelector('input:checked')?.value||'';else answer=card.querySelector('.ll-short')?.value.trim()||'';if(!answer){cfg.notify?.('请先填写答案',true);return;}const submit=card.querySelector('[data-act="submit"]');submit.disabled=true;submit.textContent='提交中…';let result,feedback,evidence='';if(q.type==='single_choice'){const ok=q.correctOptionIds.includes(answer);result=ok?'correct':'incorrect';feedback=(ok?'回答正确。':'还需要再想一想。')+(q.explanation?' '+q.explanation:'');evidence=q.anchor?.quote||fmt(q.atMs);}else{result='等待反馈';feedback='回答已保存，正在生成课程内反馈…';}
      let row={interaction_id:q.id,revision:q.revision,type:q.type,answer,result,feedback,evidence,at_ms:q.atMs,created:Date.now()};attempts.set(q.id,row);render();renderMarkers();
      const rid=cfg.getRecordingId?.();if(rid){try{row=await api('/api/learn/'+encodeURIComponent(rid)+'/attempts',{method:'POST',body:JSON.stringify({...access(),interaction_id:q.id,revision:q.revision,answer,context:cfg.getContext?.()})});attempts.set(q.id,row);render();renderMarkers();}catch(e){row.feedback+='\n联网保存失败：'+e.message;render();cfg.notify?.('回答未同步，内容已保留，可再次提交',true);}}}
    async function askQuestion(){const ta=panel.querySelector('.ll-ask textarea'),button=panel.querySelector('.ll-ask button'),text=ta.value.trim();if(!text||button.disabled)return;pause();setCollapsed(false);button.disabled=true;button.textContent='回答中…';const rid=cfg.getRecordingId?.();const local={id:'local_'+uid(),question:text,at_ms:Math.round(cfg.getPlaybackMs?.()||0),status:'pending',ai_answer:'正在依据课程内容回答…',created:Date.now()};asked.push(local);ta.value='';tab='records';panel.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab==='records'));render();if(!rid){button.disabled=false;button.textContent='提问';return;}try{const row=await api('/api/learn/'+encodeURIComponent(rid)+'/questions',{method:'POST',body:JSON.stringify({...access(),question:text,context:cfg.getContext?.()})});asked[asked.indexOf(local)]=row;render();}catch(e){local.ai_answer='服务器提交失败：'+e.message;ta.value=text;render();cfg.notify?.('提问失败，问题已放回输入框',true);}finally{button.disabled=false;button.textContent='提问';}}
    function renderRecords(){let h='';for(const q of questions){const a=attempts.get(q.id),state=a?'已回答':'待回答';h+='<div class="ll-record" data-seek="'+q.atMs+'"><div class="ll-record-title">'+esc(q.prompt)+'</div><div class="ll-record-meta">'+fmt(q.atMs)+' <span class="ui-state '+(a?'success':'warning')+'">'+state+'</span></div>'+(a?'<div class="ll-record-answer">'+esc(a.answer)+'\n'+esc(a.feedback||'')+'</div>':'')+'</div>';}for(const q of asked){h+='<div class="ll-record" data-seek="'+(q.at_ms||0)+'"><div class="ll-record-title">我的提问：'+esc(q.question)+'</div><div class="ll-record-meta">'+fmt(q.at_ms||0)+' <span class="ui-state '+(q.author_reply?'success':'warning')+'">'+esc(q.author_reply?'作者已回复':q.status||'等待反馈')+'</span></div><div class="ll-record-answer">'+esc(q.ai_answer||'')+'</div>'+(q.author_reply?'<div class="ll-author-reply"><b>作者已补充</b><br>'+esc(q.author_reply)+'</div>':'')+'</div>';}body.innerHTML=h||'<div class="ll-empty">还没有学习记录</div>';body.querySelectorAll('[data-seek]').forEach(x=>x.onclick=()=>cfg.seekTo?.(Number(x.dataset.seek)));}
    function tick(ms){if(!questions.length)return;const jump=Math.abs(ms-lastMs)>2500;let upcoming=questions.find(q=>!attempts.has(q.id)&&ms<q.atMs&&q.atMs-ms<=q.previewMs),nextPreview=upcoming?.id||'';if(nextPreview!==previewed){previewed=nextPreview;render();}if(!jump&&cfg.isPlaying?.()){const due=questions.find(q=>!attempts.has(q.id)&&!q._shown&&lastMs<q.atMs&&ms>=q.atMs);if(due){due._shown=true;showQuestion(due,true);saveEvent('checkpoint',ms,due.id);}}if(!completed&&course.duration&&ms>=course.duration*1000-250){completed=true;saveEvent('complete',ms);}lastMs=ms;}
    function onSeek(ms){if(ms<lastMs-5000)saveEvent('replay',ms);lastMs=ms;questions.forEach(q=>{if(!attempts.has(q.id)&&q.atMs<=ms)q._shown=true;});render();}
    function saveEvent(type,position,interactionId){const rid=cfg.getRecordingId?.();if(!rid)return;fetch('/api/learn/'+encodeURIComponent(rid)+'/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...access(),type,position_ms:Math.round(position||0),interaction_id:interactionId||null})}).catch(()=>{});}

    // ----- authoring -----
    const modal=document.createElement('div');modal.className='ll-author-modal';modal.innerHTML='<div class="ll-author-card"><div class="ll-author-head"><strong>互动题审核</strong><button data-gen>AI 生成</button><button data-add>＋ 新增</button><button data-close>×</button></div><div class="ll-author-list"></div><div class="ll-author-foot"><button data-cancel>取消</button><button class="primary" data-save>确认并写入课程</button></div></div>';document.body.appendChild(modal);
    const authorBtn=document.createElement('button');authorBtn.type='button';authorBtn.textContent='互动题';authorBtn.title='AI 生成并审核时间轴题目';cfg.authorActions?.insertBefore(authorBtn,cfg.authorActions.lastElementChild);authorBtn.onclick=()=>{renderAuthor();modal.classList.add('show');};
    modal.querySelector('[data-close]').onclick=modal.querySelector('[data-cancel]').onclick=()=>modal.classList.remove('show');modal.querySelector('[data-add]').onclick=()=>{authorQuestions.push(blankQuestion());renderAuthor();};modal.querySelector('[data-gen]').onclick=generateQuestions;modal.querySelector('[data-save]').onclick=saveAuthor;
    function blankQuestion(){return{id:uid(),revision:1,type:'single_choice',atMs:Math.round((cfg.getAuthorContext?.().durationMs||60000)/2),previewMs:30000,prompt:'',options:[{id:'a',text:''},{id:'b',text:''}],correctOptionIds:['a'],explanation:'',rubric:'',anchor:{fileIndex:0,quote:''},approved:false};}
    function renderAuthor(){const list=modal.querySelector('.ll-author-list');list.innerHTML=authorQuestions.map((q,i)=>{const options=q.options||[],correct=(q.correctOptionIds||[])[0]||'a';return '<div class="ll-edit-q" data-i="'+i+'"><label>题型</label><select data-k="type"><option value="single_choice" '+(q.type==='single_choice'?'selected':'')+'>单选</option><option value="short_answer" '+(q.type==='short_answer'?'selected':'')+'>简答</option></select><label>出现时间</label><input data-k="atTime" inputmode="numeric" value="'+fmt(q.atMs)+'" placeholder="1:30"><label>题目</label><textarea data-k="prompt">'+esc(q.prompt)+'</textarea><label>选项</label><textarea data-k="optionsText" placeholder="每行一个选项">'+esc(options.map(o=>o.text).join('\n'))+'</textarea><label>正确答案</label><select data-k="correct">'+options.map(o=>'<option value="'+esc(o.id)+'" '+(o.id===correct?'selected':'')+'>'+esc(o.text||o.id)+'</option>').join('')+'</select><label>评分标准</label><textarea data-k="rubric">'+esc(q.rubric||'')+'</textarea><label>答案解释</label><textarea data-k="explanation">'+esc(q.explanation||'')+'</textarea><label>原文锚点</label><input data-k="quote" value="'+esc(q.anchor?.quote||'')+'"><div class="wide"><label><input data-k="approved" type="checkbox" '+(q.approved?'checked':'')+'> 作者确认发布</label> <button data-del>删除</button></div></div>'}).join('')||'<div class="ll-empty">还没有题目</div>';list.querySelectorAll('[data-i]').forEach(card=>{card.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>updateCard(card));card.querySelector('[data-del]').onclick=()=>{authorQuestions.splice(Number(card.dataset.i),1);renderAuthor();};});}
    function updateCard(card){const q=authorQuestions[Number(card.dataset.i)],get=k=>card.querySelector('[data-k="'+k+'"]');const prev=JSON.stringify(q);q.type=get('type').value;q.atMs=parseTime(get('atTime').value);q.prompt=get('prompt').value.trim();q.rubric=get('rubric').value.trim();q.explanation=get('explanation').value.trim();q.anchor={...(q.anchor||{}),quote:get('quote').value.trim()};q.approved=get('approved').checked;const lines=get('optionsText').value.split('\n').map(s=>s.trim()).filter(Boolean);q.options=lines.map((text,i)=>({id:String.fromCharCode(97+i),text}));q.correctOptionIds=[get('correct').value||'a'];if(prev!==JSON.stringify(q))q.revision=Math.max(1,Number(q.revision)||1)+1;}
    async function generateQuestions(){const b=modal.querySelector('[data-gen]');b.disabled=true;b.textContent='生成中…';try{const ctx=cfg.getAuthorContext?.()||{};const d=await api('/generate-interactions',{method:'POST',body:JSON.stringify(ctx)});authorQuestions=normalize(d.interactions).map(q=>({...q,approved:false}));renderAuthor();}catch(e){cfg.notify?.('互动题生成失败：'+e.message,true);}finally{b.disabled=false;b.textContent='AI 生成';}}
    function saveAuthor(){modal.querySelectorAll('[data-i]').forEach(updateCard);for(const q of authorQuestions){if(q.approved&&(!q.prompt||(q.type==='single_choice'&&q.options.length<2))){cfg.notify?.('已确认题目必须填写题干和至少两个选项',true);return;}}questions=normalize(authorQuestions.filter(q=>q.approved));modal.classList.remove('show');renderMarkers();cfg.onQuestionsChanged?.(exportQuestions());cfg.notify?.('已写入 '+questions.length+' 道互动题；生成讲解或导出时会随课程保存');}
    function exportQuestions(){return normalize(authorQuestions.filter(q=>q.approved)).map(q=>structuredClone(q));}
    if(window.LectureUI){LectureUI.iconButton(modal.querySelector('[data-close]'),'close','关闭');LectureUI.setupModal(modal,modal.querySelector('.ll-author-card'),()=>modal.classList.remove('show'));}
    return{setCourse,tick,onSeek,saveEvent,exportQuestions,openAuthor:()=>authorBtn.click(),clearAuthor(){authorQuestions=[];questions=[];renderMarkers();}};
  }
  window.LectureLiteInteractions={create};
})();
