(function(){
  'use strict';
  const icons={help:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.3 2.3 0 1 1 3.2 2.1c-.8.4-1 1-1 1.7"/><path d="M12 16.8h.01"/>',close:'<path d="m7 7 10 10M17 7 7 17"/>',chevron:'<path d="m9 6 6 6-6 6"/>',star:'<path d="m12 3 2.75 5.57 6.15.9-4.45 4.33 1.05 6.12L12 17.03l-5.5 2.89 1.05-6.12L3.1 9.47l6.15-.9L12 3Z"/>',eye:'<path d="M3 12s3.2-5 9-5 9 5 9 5-3.2 5-9 5-9-5-9-5Z"/><circle cx="12" cy="12" r="2.2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A7 7 0 0 0 15 6l-.4-2.6h-4L10 6a7 7 0 0 0-1.5 1.1l-2.4-1-2 3.4L6.2 11a7 7 0 0 0 0 2l-2.1 1.5 2 3.4 2.4-1A7 7 0 0 0 10 18l.5 2.6h4L15 18a7 7 0 0 0 1.5-1.1l2.4 1 2-3.4-2-1.5a7 7 0 0 0 .1-1Z"/>'};
  const svg=name=>'<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true">'+icons[name]+'</svg>';
  function iconButton(el,name,label){if(!el)return;el.innerHTML=svg(name);el.classList.add('ui-icon-only');el.setAttribute('aria-label',label);el.title=label;}
  let lastFocus=null,scrollLock=0;
  function lock(){if(scrollLock++===0)document.documentElement.style.overflow='hidden'}
  function unlock(){if(--scrollLock<=0){scrollLock=0;document.documentElement.style.overflow=''}}
  function confirmDialog(message,opts={}){return new Promise(resolve=>{lastFocus=document.activeElement;lock();const root=document.createElement('div');root.className='ui-modal';root.innerHTML='<div class="ui-dialog" role="alertdialog" aria-modal="true"><div class="ui-dialog-head"></div><div class="ui-dialog-body"></div><div class="ui-dialog-actions"><button data-cancel>取消</button><button data-ok>确认</button></div></div>';root.querySelector('.ui-dialog-head').textContent=opts.title||'请确认';root.querySelector('.ui-dialog-body').textContent=message;const ok=root.querySelector('[data-ok]');ok.textContent=opts.confirmText||'确认';if(opts.danger)ok.classList.add('danger');const finish=value=>{root.remove();unlock();lastFocus?.focus?.();resolve(value)};root.querySelector('[data-cancel]').onclick=()=>finish(false);ok.onclick=()=>finish(true);root.onclick=e=>{if(e.target===root)finish(false)};root.onkeydown=e=>{if(e.key==='Escape')finish(false)};document.body.appendChild(root);root.querySelector('[data-cancel]').focus();});}
  function setupPassword(input){if(!input||input.parentElement?.classList.contains('ui-password'))return;const wrap=document.createElement('div');wrap.className='ui-password';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const b=document.createElement('button');b.type='button';b.className='ui-password-toggle ui-icon-only';b.innerHTML=svg('eye');b.title='显示密码';b.setAttribute('aria-label','显示密码');b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.title=b.getAttribute('aria-label')=show?'隐藏密码':'显示密码'};wrap.appendChild(b)}
  function setupStatus(source){if(!source)return;source.classList.add('ui-enhanced-source');const stack=document.createElement('div');stack.className='ui-toast-stack';document.body.appendChild(stack);let last='';new MutationObserver(()=>{const msg=source.textContent.trim();if(!msg||msg===last)return;last=msg;const busy=!/^(已|完成|成功|失败)/.test(msg)&&/正在|生成中|上传|压缩|渲染|转换|加载/.test(msg);let progress=document.querySelector('.ui-task-progress');if(busy){if(!progress){progress=document.createElement('div');progress.className='ui-task-progress';progress.innerHTML='<span></span><div class="track"><div class="fill"></div></div>';const anchor=document.querySelector('.workflow-hint');(anchor||document.querySelector('header')).after(progress)}const m=msg.match(/(\d{1,3})%/);progress.classList.add('show');progress.classList.toggle('indeterminate',!m);progress.querySelector('span').textContent=msg;progress.style.setProperty('--progress',(m?Math.min(100,+m[1]):18)+'%');return}if(progress)progress.classList.remove('show','indeterminate');const t=document.createElement('div');t.className='ui-toast '+(source.classList.contains('err')?'error':/完成|成功|已保存|已复制|已添加|已恢复|已加载/.test(msg)?'success':'');t.innerHTML='<span></span><button aria-label="关闭">×</button>';t.querySelector('span').textContent=msg;t.querySelector('button').onclick=()=>t.remove();stack.appendChild(t);setTimeout(()=>{t.classList.add('out');setTimeout(()=>t.remove(),200)},3200)}).observe(source,{childList:true,characterData:true,subtree:true,attributes:true});}
  function setupModal(root,card,close){if(!root||!card)return;const openObserver=new MutationObserver(()=>{const shown=root.classList.contains('show');if(shown){lastFocus=document.activeElement;lock();setTimeout(()=>root.querySelector('button,input,textarea,select')?.focus(),0)}else{unlock();lastFocus?.focus?.()}});openObserver.observe(root,{attributes:true,attributeFilter:['class']});root.addEventListener('keydown',e=>{if(e.key==='Escape'&&root.classList.contains('show'))close?.()});}
  window.LectureUI={svg,iconButton,confirm:confirmDialog,setupPassword,setupStatus,setupModal};
  document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add(location.pathname.includes('home')?'page-home':'page-editor');iconButton(document.getElementById('helpBtn'),'help','帮助');iconButton(document.getElementById('feedbackClose'),'close','关闭');document.querySelectorAll('input[type=password]').forEach(setupPassword);setupStatus(document.getElementById('status'));const feedback=document.getElementById('feedbackModal');if(feedback)setupModal(feedback,feedback.querySelector('.feedback-card'),()=>feedback.classList.remove('show'));const auth=document.getElementById('authGate');if(auth)setupModal(auth,auth.querySelector('.card'));const intro=document.getElementById('intro');if(intro)setupModal(intro,intro.querySelector('.card'),()=>intro.classList.remove('show'))});
})();
